// <auto-generated />
namespace LMSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MissionAddBool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissionAddBool));
        
        string IMigrationMetadata.Id
        {
            get { return "202203080714446_MissionAddBool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
